apiVersion: v1
kind: Pod
metadata:
  name: tf
spec:
  containers:
    - name: nvidia
      image: 192.168.1.153:5000/jetson-jupyter-tensorflow:v44 
      command: [ "sleep" ]
      args: [ "1d" ]
  nodeSelector:
    kubernetes.io/hostname: jetson03
